# Generated by Django 3.1.4 on 2021-01-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='item',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.AddField(
            model_name='winner',
            name='bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='auctions.bid'),
            preserve_default=False,
        ),
    ]
