# Generated by Django 3.1.4 on 2021-01-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210107_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='item_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='auctions.category'),
        ),
    ]
