# Generated by Django 3.1.4 on 2021-01-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210111_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
