# Generated by Django 3.1.4 on 2021-01-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210103_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(default='Null', max_length=2000),
            preserve_default=False,
        ),
    ]
