# Generated by Django 3.1.4 on 2021-01-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210105_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
